# Generated by Django 4.1 on 2024-11-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
